-- Run in Supabase SQL Editor. RLS is enabled on every public table.
create extension if not exists pgcrypto;
create type report_status as enum ('new','confirming','accepted','assigned','in_progress','resolved','rejected');
create table public.profiles (id uuid primary key references auth.users on delete cascade, display_name text not null, role text not null default 'user' check(role in ('user','moderator','city_service','admin','business','event_organizer')), district text, reputation int not null default 0, created_at timestamptz not null default now());
create table public.reports (id uuid primary key default gen_random_uuid(), author_id uuid references public.profiles on delete set null, title text not null check(char_length(title)<=80), description text not null check(char_length(description)<=1000), category text not null, type text not null default 'problem', status report_status not null default 'new', priority text not null default 'Обычная', location text not null, latitude double precision, longitude double precision, confirmations int not null default 0, anonymous boolean not null default false, image_path text, created_at timestamptz not null default now(), resolved_at timestamptz);
create table public.report_confirmations (report_id uuid references public.reports on delete cascade, user_id uuid references public.profiles on delete cascade, created_at timestamptz not null default now(), primary key(report_id,user_id));
create table public.events (id uuid primary key default gen_random_uuid(), organizer_id uuid references public.profiles on delete set null, title text not null, description text, starts_at timestamptz not null, ends_at timestamptz, location text not null, latitude double precision, longitude double precision, price numeric(10,2) default 0, category text, image_path text, created_at timestamptz not null default now());
create table public.event_attendees (event_id uuid references public.events on delete cascade, user_id uuid references public.profiles on delete cascade, created_at timestamptz not null default now(), primary key(event_id,user_id));
create table public.comments (id uuid primary key default gen_random_uuid(), report_id uuid references public.reports on delete cascade, author_id uuid references public.profiles on delete set null, body text not null check(char_length(body)<=1000), created_at timestamptz not null default now());
create table public.notifications (id uuid primary key default gen_random_uuid(), user_id uuid references public.profiles on delete cascade, title text not null, body text, read boolean not null default false, created_at timestamptz not null default now());
alter table public.profiles enable row level security;alter table public.reports enable row level security;alter table public.report_confirmations enable row level security;alter table public.events enable row level security;alter table public.event_attendees enable row level security;alter table public.comments enable row level security;alter table public.notifications enable row level security;
create policy "profiles readable" on public.profiles for select using(true);create policy "own profile update" on public.profiles for update using(auth.uid()=id);create policy "reports readable" on public.reports for select using(true);create policy "authenticated create reports" on public.reports for insert to authenticated with check(auth.uid()=author_id);create policy "author edits open report" on public.reports for update to authenticated using(auth.uid()=author_id and status in ('new','confirming'));create policy "events readable" on public.events for select using(true);create policy "organizer creates event" on public.events for insert to authenticated with check(auth.uid()=organizer_id);create policy "comments readable" on public.comments for select using(true);create policy "authenticated comments" on public.comments for insert to authenticated with check(auth.uid()=author_id);create policy "own notifications" on public.notifications for select to authenticated using(auth.uid()=user_id);create policy "own notification update" on public.notifications for update to authenticated using(auth.uid()=user_id);create policy "confirmations readable" on public.report_confirmations for select using(true);create policy "confirm once" on public.report_confirmations for insert to authenticated with check(auth.uid()=user_id);create policy "attendance readable" on public.event_attendees for select using(true);create policy "own attendance" on public.event_attendees for all to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);
create or replace function public.sync_confirmation_count() returns trigger language plpgsql security definer set search_path=public as $$ begin update reports set confirmations=(select count(*) from report_confirmations where report_id=coalesce(new.report_id,old.report_id)),status=case when status='new' then 'confirming' else status end where id=coalesce(new.report_id,old.report_id);return coalesce(new,old);end;$$;
create trigger confirmation_count after insert or delete on public.report_confirmations for each row execute function public.sync_confirmation_count();
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,display_name) values(new.id,coalesce(new.raw_user_meta_data->>'name','Житель Актау'));return new;end;$$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('report-media','report-media',true,10485760,array['image/jpeg','image/png','image/webp']) on conflict(id) do nothing;
create policy "public media read" on storage.objects for select using(bucket_id='report-media');create policy "authenticated media upload" on storage.objects for insert to authenticated with check(bucket_id='report-media' and (storage.foldername(name))[1]=auth.uid()::text);
