import http from 'node:http';import {readFile,writeFile,mkdir} from 'node:fs/promises';import {existsSync,createReadStream} from 'node:fs';import {extname,join,normalize} from 'node:path';import {randomUUID,createHash} from 'node:crypto';
const PORT=process.env.PORT||3000,ROOT=join(process.cwd(),'public'),DATA=join(process.cwd(),'data'),DB=join(DATA,'db.json');
await mkdir(DATA,{recursive:true});if(!existsSync(DB))await writeFile(DB,JSON.stringify({reports:[],users:[{id:'demo',name:'Зейнеп Серк',email:'demo@aqtau.local'}],events:[]},null,2));
const types={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json','.webmanifest':'application/manifest+json','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.webp':'image/webp'};
const readDB=async()=>JSON.parse(await readFile(DB,'utf8'));const saveDB=db=>writeFile(DB,JSON.stringify(db,null,2));const send=(res,status,data,type='application/json')=>{res.writeHead(status,{'Content-Type':type,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'strict-origin-when-cross-origin'});res.end(type==='application/json'?JSON.stringify(data):data)};
const body=req=>new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>1e6)reject(new Error('too large'))});req.on('end',()=>{try{resolve(JSON.parse(s||'{}'))}catch{reject(new Error('bad json'))}})});
async function supabase(path,options={}){if(!process.env.SUPABASE_URL||!process.env.SUPABASE_ANON_KEY)return null;const r=await fetch(`${process.env.SUPABASE_URL}${path}`,{...options,headers:{apikey:process.env.SUPABASE_ANON_KEY,Authorization:`Bearer ${process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_ANON_KEY}`,'Content-Type':'application/json',Prefer:'return=representation',...(options.headers||{})}});if(!r.ok)throw new Error(await r.text());return r.status===204?{}:r.json()}
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');if(url.pathname==='/api/health')return send(res,200,{ok:true,mode:process.env.SUPABASE_URL?'supabase':'demo',time:new Date().toISOString()});
if(url.pathname==='/api/reports'&&req.method==='GET'){const cloud=await supabase('/rest/v1/reports?select=*&order=created_at.desc');if(cloud)return send(res,200,cloud);const db=await readDB();return send(res,200,db.reports)}
if(url.pathname==='/api/reports'&&req.method==='POST'){const input=await body(req);if(!input.title||!input.description||!input.location)return send(res,422,{error:'Заполните обязательные поля'});const record={id:randomUUID(),title:String(input.title).slice(0,80),description:String(input.description).slice(0,1000),location:String(input.location).slice(0,160),category:String(input.category||'Другое'),priority:String(input.priority||'Обычная'),type:String(input.type||'problem'),status:'new',confirmations:0,created_at:new Date().toISOString()};const cloud=await supabase('/rest/v1/reports',{method:'POST',body:JSON.stringify(record)});if(cloud)return send(res,201,cloud[0]||record);const db=await readDB();db.reports.unshift(record);await saveDB(db);return send(res,201,record)}
if(url.pathname.startsWith('/api/reports/')&&url.pathname.endsWith('/confirm')&&req.method==='POST'){const id=url.pathname.split('/')[3],db=await readDB(),r=db.reports.find(x=>x.id===id);if(!r)return send(res,404,{error:'not found'});r.confirmations++;await saveDB(db);return send(res,200,r)}
if(url.pathname==='/api/auth/register'&&req.method==='POST'){const input=await body(req);if(process.env.SUPABASE_URL){const cloud=await supabase('/auth/v1/signup',{method:'POST',body:JSON.stringify({email:input.email,password:input.password,data:{name:input.name}})});return send(res,201,cloud)}if(!input.email||!input.password)return send(res,422,{error:'Email и пароль обязательны'});const db=await readDB();if(db.users.some(u=>u.email===input.email))return send(res,409,{error:'Пользователь уже существует'});const user={id:randomUUID(),email:input.email,name:input.name||'Житель Актау',password_hash:createHash('sha256').update(input.password).digest('hex')};db.users.push(user);await saveDB(db);return send(res,201,{user:{id:user.id,email:user.email,name:user.name},demo:true})}
if(url.pathname==='/api/auth/login'&&req.method==='POST'){const input=await body(req);if(process.env.SUPABASE_URL){const cloud=await supabase('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email:input.email,password:input.password})});return send(res,200,cloud)}const db=await readDB(),hash=createHash('sha256').update(input.password||'').digest('hex'),u=db.users.find(x=>x.email===input.email&&x.password_hash===hash);if(!u)return send(res,401,{error:'Неверные данные'});return send(res,200,{user:{id:u.id,email:u.email,name:u.name},token:'demo-'+randomUUID(),demo:true})}
if(url.pathname.startsWith('/api/'))return send(res,404,{error:'not found'});
let path=normalize(decodeURIComponent(url.pathname)).replace(/^(\.\.(\/|\\|$))+/, '');if(path==='/'||!extname(path))path='/index.html';const file=join(ROOT,path);if(!file.startsWith(ROOT)||!existsSync(file))return send(res,404,'Not found','text/plain');res.writeHead(200,{'Content-Type':types[extname(file)]||'application/octet-stream','Cache-Control':extname(file)==='.html'?'no-cache':'public, max-age=3600'});createReadStream(file).pipe(res)}catch(err){console.error(err);send(res,500,{error:'Внутренняя ошибка сервера'})}});
server.listen(PORT,()=>console.log(`Aqtau Pulse: http://localhost:${PORT} (${process.env.SUPABASE_URL?'Supabase':'demo'} mode)`));
