import React,{useMemo,useState,useEffect}from'react';
import{MapContainer,TileLayer,Marker,Popup,ZoomControl}from'react-leaflet';
import L from'leaflet';
import{motion,AnimatePresence}from'motion/react';
import{Map,Radio,Tickets,Compass,Users,LayoutDashboard,Search,Bell,Plus,LocateFixed,Wind,Navigation,ShieldAlert,CalendarDays,Camera,CheckCircle2,Clock3,MapPin,ChevronRight,Heart,MessageCircle,Bookmark,SlidersHorizontal,X,ChevronDown,Languages,Sun,Moon,TrendingUp,Route,Building2,Leaf,Bus,Accessibility,MoreHorizontal,ArrowUpRight,Sparkles,Upload,Send,Eye,Download,LifeBuoy,Menu,Check,AlertTriangle}from'lucide-react';

const copy={
ru:{search:'Найти событие, место или проблему',map:'Карта',feed:'Пульс',cases:'Обращения',events:'События',explore:'Открыть Актау',community:'Сообщества',dashboard:'Для служб',live:'ГОРОД В РЕАЛЬНОМ ВРЕМЕНИ',near:'Что происходит рядом',updated:'128 активных точек · обновлено сейчас',report:'Сообщить',moment:'Момент',all:'Всё',problems:'Проблемы',safety:'Безопасность',places:'Места',offers:'Акции',around:'Рядом',important:'Важное',following:'Подписки',create:'Создать публикацию',today:'Сегодня в Актау',route:'Маршрут',confirm:'Подтвердить',resolved:'Решено',working:'В работе',newReport:'Новое обращение',title:'Заголовок',description:'Описание',location:'Местоположение',category:'Категория',publish:'Опубликовать',cancel:'Отмена',language:'Язык'},
kz:{search:'Іс-шараны, орынды немесе мәселені іздеу',map:'Карта',feed:'Қала тынысы',cases:'Өтініштер',events:'Оқиғалар',explore:'Ақтауды ашу',community:'Қауымдастықтар',dashboard:'Қызметтерге',live:'ҚАЛА НАҚТЫ УАҚЫТТА',near:'Жақын жерде не болып жатыр?',updated:'128 белсенді нүкте · жаңа ғана жаңартылды',report:'Хабарлау',moment:'Сәт',all:'Барлығы',problems:'Мәселелер',safety:'Қауіпсіздік',places:'Орындар',offers:'Акциялар',around:'Жақын',important:'Маңызды',following:'Жазылымдар',create:'Жарияланым жасау',today:'Бүгін Ақтауда',route:'Бағыт',confirm:'Растау',resolved:'Шешілді',working:'Жұмыста',newReport:'Жаңа өтініш',title:'Тақырып',description:'Сипаттама',location:'Орналасқан жері',category:'Санат',publish:'Жариялау',cancel:'Бас тарту',language:'Тіл'},
en:{search:'Find an event, place or city issue',map:'Map',feed:'Pulse',cases:'Reports',events:'Events',explore:'Explore Aktau',community:'Communities',dashboard:'City services',live:'THE CITY, LIVE',near:'What is happening nearby?',updated:'128 active signals · updated now',report:'Report',moment:'Moment',all:'All',problems:'Issues',safety:'Safety',places:'Places',offers:'Offers',around:'Nearby',important:'Important',following:'Following',create:'Create post',today:'Today in Aktau',route:'Route',confirm:'Confirm',resolved:'Resolved',working:'In progress',newReport:'New city report',title:'Title',description:'Description',location:'Location',category:'Category',publish:'Publish',cancel:'Cancel',language:'Language'}};
const langs=[['ru','RU'],['kz','ҚАЗ'],['en','EN']];
const reports=[
{id:1,pos:[43.648,51.158],type:'urgent',title:'Открытый люк у школы №17',place:'12 мкр. · 8 мин',body:'Высокий риск: рядом школа и остановка.',count:14,status:'working',icon:AlertTriangle},
{id:2,pos:[43.654,51.171],type:'event',title:'Sunset Run Aktau',place:'Набережная · 19:00',body:'Пять километров у моря на закате.',count:84,status:'event',icon:CalendarDays},
{id:3,pos:[43.640,51.151],type:'safe',title:'Площадка очищена',place:'14 мкр. · 24 мин',body:'Служба добавила фото результата.',count:39,status:'resolved',icon:CheckCircle2},
{id:4,pos:[43.645,51.181],type:'place',title:'Скальная тропа',place:'Маршрут №3 · 1,8 км',body:'Панорамная точка у Каспийского моря.',count:126,status:'place',icon:Compass},
{id:5,pos:[43.658,51.149],type:'danger',title:'Сильный боковой ветер',place:'Побережье · 3 мин',body:'Порывы до 18 м/с. Будьте осторожны.',count:21,status:'new',icon:Wind},
{id:6,pos:[43.636,51.169],type:'issue',title:'Не работает фонарь',place:'17 мкр. · 18 мин',body:'Передано службе городского освещения.',count:7,status:'working',icon:Building2}
];
const feed=[reports[4],reports[0],reports[1],reports[2]];
const nav=[['map',Map],['feed',Radio],['cases',Tickets],['events',CalendarDays],['explore',Compass],['community',Users],['dashboard',LayoutDashboard]];
const icons={urgent:'#ff8a4c',event:'#4ea2ff',safe:'#39c486',place:'#9a7cf0',danger:'#ff5f68',issue:'#f8b44f'};
function pin(type){return L.divIcon({className:'pulse-marker-wrap',html:`<div class="pulse-marker ${type}"><span></span></div>`,iconSize:[38,46],iconAnchor:[19,42],popupAnchor:[0,-38]})}
function Count({to,suffix=''}){const[n,setN]=useState(0);useEffect(()=>{let s=0;const id=setInterval(()=>{s+=Math.max(1,Math.ceil(to/28));if(s>=to){s=to;clearInterval(id)}setN(s)},22);return()=>clearInterval(id)},[to]);return<>{n}{suffix}</>}
function App(){const[lang,setLang]=useState('ru'),[view,setView]=useState('map'),[filter,setFilter]=useState('all'),[tab,setTab]=useState('around'),[modal,setModal]=useState(false),[dark,setDark]=useState(true),[notice,setNotice]=useState(false),[saved,setSaved]=useState(new Set()),[liked,setLiked]=useState(new Set()),[toast,setToast]=useState(''),[menu,setMenu]=useState(false);const t=copy[lang];
useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light'},[dark]);useEffect(()=>{if(toast){const x=setTimeout(()=>setToast(''),2800);return()=>clearTimeout(x)}},[toast]);
const shown=useMemo(()=>reports.filter(r=>filter==='all'||filter==='problems'&&['urgent','issue'].includes(r.type)||filter==='safety'&&r.type==='danger'||filter===r.type),[filter]);
const action=m=>{setToast(m)};
return <div className="app">
<header className="topbar"><button className="logo" onClick={()=>setView('map')}><i><span></span><span></span><span></span></i><b>Aqtau<span>Pulse</span></b></button><label className="search"><Search size={17}/><input placeholder={t.search}/><kbd>⌘ K</kbd></label><div className="top-actions"><button className="round" onClick={()=>setDark(!dark)} aria-label="theme">{dark?<Sun/>:<Moon/>}</button><div className="lang"><Languages size={17}/>{langs.map(([k,v])=><button key={k} className={lang===k?'active':''} onClick={()=>setLang(k)}>{v}</button>)}</div><button className="round bell" onClick={()=>setNotice(!notice)}><Bell/><i>3</i></button><button className="user" onClick={()=>setView('profile')}><span>ZS</span><div><b>Зейнеп</b><small>1 240 XP</small></div></button><button className="mobile-menu" onClick={()=>setMenu(!menu)}><Menu/></button></div></header>
<aside className={`sidebar ${menu?'open':''}`}><nav>{nav.map(([id,Icon])=><button key={id} className={view===id?'active':''} onClick={()=>{setView(id);setMenu(false)}}><Icon/><span>{t[id]}</span>{id==='cases'&&<em>4</em>}</button>)}</nav><div className="side-spacer"/><motion.div className="impact" whileHover={{y:-3}}><div className="impact-top"><span><Sparkles size={16}/></span><small>72%</small></div><b>Ваш вклад меняет город</b><p>7 подтверждений · 3 проблемы решены</p><i><span/></i><small>До уровня «Эксперт» — 280 XP</small></motion.div><button className="sos" onClick={()=>confirm('При угрозе жизни позвоните 112. Открыть набор номера?')&&(location.href='tel:112')}><LifeBuoy/><span><b>Экстренная помощь</b><small>Позвонить 112</small></span></button></aside>
<main><AnimatePresence mode="wait"><motion.section key={view} initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}} transition={{duration:.28,ease:[.22,1,.36,1]}} className="view">
{view==='map'&&<MapView t={t} shown={shown} filter={filter} setFilter={setFilter} tab={tab} setTab={setTab} onCreate={()=>setModal(true)} action={action}/>} 
{view==='feed'&&<FeedPage t={t} liked={liked} setLiked={setLiked} saved={saved} setSaved={setSaved} action={action} onCreate={()=>setModal(true)}/>} 
{view==='cases'&&<CasesPage t={t} onCreate={()=>setModal(true)} action={action}/>} 
{view==='events'&&<EventsPage t={t} action={action}/>} 
{view==='explore'&&<ExplorePage t={t} action={action}/>} 
{view==='community'&&<CommunityPage action={action}/>} 
{view==='dashboard'&&<DashboardPage action={action}/>} 
{view==='profile'&&<ProfilePage/>}
</motion.section></AnimatePresence></main>
<nav className="mobile-nav">{nav.slice(0,2).map(([id,Icon])=><button key={id} className={view===id?'active':''} onClick={()=>setView(id)}><Icon/><small>{t[id]}</small></button>)}<button className="mobile-plus" onClick={()=>setModal(true)}><Plus/></button>{nav.slice(3,5).map(([id,Icon])=><button key={id} className={view===id?'active':''} onClick={()=>setView(id)}><Icon/><small>{t[id]}</small></button>)}</nav>
<AnimatePresence>{notice&&<motion.aside className="notification-panel" initial={{x:400}} animate={{x:0}} exit={{x:400}} transition={{type:'spring',damping:28}}><header><div><span className="kicker">ОБНОВЛЕНИЯ</span><h2>Уведомления</h2></div><button onClick={()=>setNotice(false)}><X/></button></header>{[['Ваше обращение принято','Фонарь в 17 мкр. назначен службе','2 мин'],['Событие начинается через час','Sunset Run Aktau · Набережная','18 мин'],['Новый уровень близко','До «Городского эксперта» 280 XP','1 ч']].map((x,i)=><div className="notice" key={i}><i><Bell size={16}/></i><div><b>{x[0]}</b><p>{x[1]}</p><small>{x[2]}</small></div></div>)}</motion.aside>}</AnimatePresence>
<AnimatePresence>{modal&&<CreateModal t={t} close={()=>setModal(false)} done={()=>{setModal(false);action('Опубликовано на карте · +40 XP')}}/>}</AnimatePresence>
<AnimatePresence>{toast&&<motion.div className="toast" initial={{opacity:0,y:30,scale:.96}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:20}}><CheckCircle2/><span><b>Готово</b><small>{toast}</small></span></motion.div>}</AnimatePresence>
</div>}
function MapView({t,shown,filter,setFilter,tab,setTab,onCreate,action}){const filters=[['all',t.all],['problems',t.problems],['event',t.events],['safety',t.safety],['place',t.places]];return <div className="map-page"><div className="map-hero"><div className="map-title"><span className="kicker"><i/> {t.live}</span><h1>{t.near}</h1><p>{t.updated}</p></div><div className="weather"><Wind/><span><b>+24°</b><small>8 м/с · море спокойно</small></span></div><div className="filter-row">{filters.map(([k,v])=><button key={k} className={filter===k?'active':''} onClick={()=>setFilter(k)}><i style={{background:k==='all'?'#fff':icons[k]||'#4ea2ff'}}/>{v}<small>{k==='all'?128:k==='problems'?34:k==='event'?18:k==='safety'?6:52}</small></button>)}</div><MapContainer center={[43.648,51.165]} zoom={14} zoomControl={false} className="real-map"><TileLayer attribution='&copy; OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><ZoomControl position="bottomleft"/>{shown.map(r=><Marker key={r.id} position={r.pos} icon={pin(r.type)}><Popup><div className="map-popup"><span className={`tag ${r.type}`}>{r.status}</span><h3>{r.title}</h3><p><MapPin size={13}/>{r.place}</p><p>{r.body}</p><div><b>{r.count} подтверждений</b><button onClick={()=>action('Безопасный маршрут построен')}><Navigation size={14}/>{t.route}</button></div></div></Popup></Marker>)}</MapContainer><button className="locate" onClick={()=>action('Местоположение найдено · точность 18 м')}><LocateFixed/><span>Моё местоположение</span></button><div className="map-status"><span><i/> LIVE</span><small>Данные сообщества обновляются каждые 15 секунд</small></div></div><aside className="pulse-panel"><header><div><span className="kicker">AQTAU PULSE</span><h2>{t.today}</h2></div><button><SlidersHorizontal/></button></header><div className="quick"><button onClick={onCreate}><span className="orange"><Plus/></span><b>{t.report}</b><small>о проблеме</small></button><button onClick={()=>action('Камера готова')}><span className="blue"><Camera/></span><b>{t.moment}</b><small>поделиться</small></button><button onClick={()=>action('Форма события открыта')}><span className="violet"><CalendarDays/></span><b>{t.events}</b><small>добавить</small></button></div><div className="panel-tabs">{['around','important','following'].map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{t[x]}</button>)}</div><div className="pulse-list">{feed.map((r,i)=><motion.article key={r.id} initial={{opacity:0,x:18}} animate={{opacity:1,x:0}} transition={{delay:i*.06}}><span className={`feed-icon ${r.type}`}><r.icon/></span><div><header><b>{r.title}</b><span>{r.place}</span></header><p>{r.body}</p><footer><button onClick={()=>action('Подтверждение учтено')}><CheckCircle2/> {r.count}</button><button><MessageCircle/> {4+i*3}</button><button onClick={()=>action('Точка открыта на карте')}>На карте <ChevronRight/></button></footer></div></motion.article>)}</div></aside></div>}
function PageHead({kicker,title,sub,button,onClick}){return <header className="page-head"><div><span className="kicker">{kicker}</span><h1>{title}</h1><p>{sub}</p></div>{button&&<button className="primary" onClick={onClick}><Plus/>{button}</button>}</header>}
function FeedPage({t,liked,setLiked,saved,setSaved,action,onCreate}){return <div className="page"><PageHead kicker={t.live} title="Пульс Актау" sub="Моменты, которые складываются в историю города." button={t.create} onClick={onCreate}/><div className="feed-layout"><div className="social-feed">{feed.slice(0,3).map((r,i)=><motion.article className="social-card" key={r.id} whileHover={{y:-4}}><header><span className="avatar">{['AN','ME','EA'][i]}</span><div><b>{['Айжан Нурова','Марат Есенов','Eco Aktau'][i]}</b><small>{r.place}</small></div><button><MoreHorizontal/></button></header><p><b>{r.title}</b><br/>{r.body}</p><div className={`post-image image-${i}`}><span><Radio/> происходит сейчас</span></div><footer><button className={liked.has(r.id)?'liked':''} onClick={()=>{const n=new Set(liked);n.has(r.id)?n.delete(r.id):n.add(r.id);setLiked(n)}}><Heart/> {26+i*18}</button><button onClick={()=>action('Комментарии открыты')}><MessageCircle/> {8+i}</button><button onClick={()=>action('Проблема подтверждена')}><CheckCircle2/> {t.confirm}</button><button className={saved.has(r.id)?'saved':''} onClick={()=>{const n=new Set(saved);n.has(r.id)?n.delete(r.id):n.add(r.id);setSaved(n)}}><Bookmark/></button></footer></motion.article>)}</div><aside className="right-rail"><div className="rail-card"><span className="kicker">В ТРЕНДЕ</span><h3>Город обсуждает</h3>{[['#ЧистыйБерег','126 публикаций'],['Sunset Run','84 участника'],['Ветер у моря','21 обновление']].map((x,i)=><div className="trend"><b>0{i+1}</b><span><strong>{x[0]}</strong><small>{x[1]}</small></span><ArrowUpRight/></div>)}</div><div className="rail-card gradient"><Sparkles/><h3>Ваш город — ваш алгоритм</h3><p>Лента учитывает район, интересы и важность сигналов.</p><button>Настроить ленту</button></div></aside></div></div>}
function CasesPage({t,onCreate,action}){const cols=[['Новое',reports.slice(0,2)],['Принято',[reports[5]]],['В работе',[reports[0],reports[3]]],['Решено',[reports[2]]]];return <div className="page"><PageHead kicker="ОТ СИГНАЛА ДО РЕЗУЛЬТАТА" title={t.cases} sub="Прозрачный путь каждого обращения — без тишины и неизвестности." button={t.newReport} onClick={onCreate}/><div className="metric-row">{[['128','Активных','+12 за неделю'],['34','В работе','6 срочных'],['87%','В срок','↑ 8%'],['2:18','Средний ответ','−34 мин']].map((x,i)=><div className="metric" key={x[1]}><small>{x[1]}</small><b>{i===0?<Count to={128}/>:x[0]}</b><span>{x[2]}</span></div>)}</div><div className="kanban">{cols.map(([name,items],c)=><section><header><b>{name}</b><span>{items.length}</span></header>{items.map(r=><motion.article key={r.id} whileHover={{y:-3,scale:1.01}} onClick={()=>action('Карточка обращения открыта')}><i style={{background:icons[r.type]}}/><span className={`tag ${r.type}`}>{r.status}</span><h3>{r.title}</h3><p><MapPin/>{r.place}</p><footer><span><Eye/> {r.count}</span><ArrowUpRight/></footer></motion.article>)}</section>)}</div></div>}
function EventsPage({t,action}){return <div className="page"><PageHead kicker="ПЛАНЫ НА НЕДЕЛЮ" title={t.events} sub="Встречайтесь, узнавайте новое и меняйте город вместе." button="Добавить событие" onClick={()=>action('Форма события открыта')}/><motion.div className="event-feature" whileHover={{scale:1.005}}><div className="orb"/><div><span className="kicker">ГЛАВНОЕ · СЕГОДНЯ 19:00</span><h2>Sunset Run Aktau</h2><p>Пять километров вдоль Каспия на закате. Свободный темп, музыка и городское сообщество.</p><button className="primary" onClick={()=>action('Добавлено в ваш календарь')}><Check/> Я пойду · 84</button></div></motion.div><div className="event-cards">{[['28','Чистый берег','Пляж Маракеш · 09:00','eco'],['30','Город у моря','Культурный центр · 18:30','talk'],['02','Ночь в музее','Музей истории · 20:00','museum']].map(x=><motion.article whileHover={{y:-6}}><div className={`event-art ${x[3]}`}><span><b>{x[0]}</b>СЕН</span></div><div><h3>{x[1]}</h3><p><MapPin/>{x[2]}</p><footer><span>52 участника</span><button onClick={()=>action('Место забронировано')}>Участвовать</button></footer></div></motion.article>)}</div></div>}
function ExplorePage({t,action}){return <div className="page"><div className="explore-hero"><motion.div initial={{opacity:0,x:-30}} animate={{opacity:1,x:0}}><span className="kicker">48 ЧАСОВ У КАСПИЯ</span><h1>Море.<br/>Скалы. <i>Актау.</i></h1><p>Персональный маршрут с безопасными тропами, событиями и местами, которые любят местные.</p><button className="primary" onClick={()=>action('Маршрут из 4 остановок построен')}><Route/> Собрать мой день</button></motion.div><div className="explore-sun"><span/></div></div><div className="itinerary">{[['09:00','Завтрак у моря','Панорамная терраса'],['10:30','Скальная тропа','Безопасный путь · 2 км'],['13:00','Музей истории','RU · KZ · EN'],['18:30','Закат на набережной','Ветер стихает к вечеру']].map((x,i)=><div><small>{x[0]}</small><i>{i+1}</i><b>{x[1]}</b><span>{x[2]}</span></div>)}</div><div className="place-cards">{[['Каспийская набережная','4.9 · 2,4 км','sea'],['Скальная тропа','4.8 · 3,1 км','rock'],['Подземная мечеть','4.9 · 42 км','desert']].map(x=><motion.article whileHover={{y:-6}}><div className={`place-art ${x[2]}`}/><div><h3>{x[0]}</h3><p>★ {x[1]}</p><button onClick={()=>action('Маршрут открыт')}><Navigation/> {t.route}</button></div></motion.article>)}</div></div>}
function CommunityPage({action}){return <div className="page"><PageHead kicker="СИЛА ЛЮДЕЙ" title="Сообщества Актау" sub="Найдите своих соседей, единомышленников и команду для добрых дел." button="Создать сообщество" onClick={()=>action('Заявка отправлена модератору')}/><div className="community-grid">{[[Leaf,'Eco Aktau','Чистый берег и переработка','892'],[Building2,'14 микрорайон','Соседские новости и помощь','1 284'],[Search,'Потеряно / найдено','Вернём вещи владельцам','2 106'],[Accessibility,'Помощь рядом','Волонтёры и добрые дела','674'],[Bus,'Удобный транспорт','Маршруты и остановки','938'],[Sparkles,'Молодой Актау','Спорт, учёба и события','1 452']].map(([Icon,name,desc,n],i)=><motion.article whileHover={{y:-5}}><span><Icon/></span><h3>{name}</h3><p>{desc}</p><footer><div className="faces"><i>AN</i><i>ME</i><i>+{n}</i></div><button onClick={e=>{e.currentTarget.textContent='Вы участник';action('Добро пожаловать в сообщество')}}>Вступить</button></footer></motion.article>)}</div></div>}
function DashboardPage({action}){return <div className="page"><PageHead kicker="ЕДИНАЯ КАРТИНА ГОРОДА" title="Оперативный центр" sub="Приоритеты, исполнители и результат — в одном живом пространстве."/><div className="metric-row">{[['94','Новых за 7 дней','+12%'],['81','Закрыто','86%'],['6','Срочных','−3'],['2:18','Ответ','−34 мин']].map(x=><div className="metric"><small>{x[1]}</small><b>{x[0]}</b><span>{x[2]}</span></div>)}</div><div className="dash-grid"><section className="chart-card"><header><div><span className="kicker">ДИНАМИКА</span><h3>Обращения за неделю</h3></div><button><Download/></button></header><div className="chart">{[45,66,52,78,61,91,74].map((h,i)=><motion.i initial={{height:0}} animate={{height:`${h}%`}} transition={{delay:i*.06,duration:.7}}><span>{['Пн','Вт','Ср','Чт','Пт','Сб','Вс'][i]}</span></motion.i>)}</div></section><section className="chart-card"><span className="kicker">AI-ПРИОРИТЕТ</span><h3>Требуют внимания</h3>{reports.slice(0,3).map(r=><div className="priority-item"><i style={{background:icons[r.type]}}/><span><b>{r.title}</b><small>{r.place}</small></span><strong>{r.count*3}</strong></div>)}<button className="outline" onClick={()=>action('Список отсортирован по риску')}>Открыть очередь <ChevronRight/></button></section></div></div>}
function ProfilePage(){return <div className="page"><div className="profile-hero"><span className="profile-avatar">ZS<i/></span><div><span className="kicker">ЖИТЕЛЬ · 14 МКР.</span><h1>Зейнеп Серк</h1><p>Городской помощник · уровень 8</p></div><div className="profile-numbers"><span><b>23</b><small>публикации</small></span><span><b>87</b><small>подтверждений</small></span><span><b>1 240</b><small>XP</small></span></div></div><div className="profile-grid"><section className="chart-card"><span className="kicker">ДОСТИЖЕНИЯ</span><h3>Ваша коллекция</h3><div className="badges"><span>♻<b>Эко-герой</b></span><span>◎<b>Знаток района</b></span><span>✓<b>Проверенный</b></span><span>★<b>Ранний участник</b></span></div></section><section className="chart-card"><span className="kicker">ВЛИЯНИЕ</span><h3>3 проблемы решены с вашей помощью</h3><p className="muted">Вы входите в 12% самых активных жителей вашего района.</p><div className="level"><span style={{width:'72%'}}/></div><small>280 XP до следующего уровня</small></section></div></div>}
function CreateModal({t,close,done}){const[step,setStep]=useState(1),[type,setType]=useState('problem');return <motion.div className="modal-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onMouseDown={e=>e.target===e.currentTarget&&close()}><motion.div className="modal" initial={{opacity:0,y:30,scale:.97}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:20}}><header><div><span className="kicker">НОВАЯ ТОЧКА · ШАГ {step} ИЗ 2</span><h2>{t.newReport}</h2></div><button onClick={close}><X/></button></header><div className="steps"><i className="active"/><i className={step===2?'active':''}/></div>{step===1?<div className="modal-body"><p className="label">Что вы хотите добавить?</p><div className="type-grid">{[['problem',AlertTriangle,'Проблема'],['moment',Camera,t.moment],['event',CalendarDays,t.events],['place',Compass,t.places]].map(([id,Icon,label])=><button className={type===id?'active':''} onClick={()=>setType(id)}><Icon/><b>{label}</b></button>)}</div><label className="upload"><Upload/><b>Перетащите фото или нажмите</b><small>JPG, PNG, WebP · до 10 МБ</small><input type="file" accept="image/*"/></label><button className="primary full" onClick={()=>setStep(2)}>Продолжить <ChevronRight/></button></div>:<form className="modal-body" onSubmit={e=>{e.preventDefault();done()}}><div className="field-row"><label><span>{t.title}</span><input required placeholder="Коротко: что произошло?"/></label><label><span>{t.category}</span><select><option>Благоустройство</option><option>Безопасность</option><option>Дороги</option><option>Экология</option></select></label></div><label><span>{t.description}</span><textarea required rows="4" placeholder="Добавьте детали, которые помогут решить проблему"/></label><label><span>{t.location}</span><div className="with-action"><input defaultValue="14 мкр., рядом с набережной"/><button type="button"><LocateFixed/></button></div></label><div className="safety-note"><ShieldAlert/><span><b>Публикация сообщества</b><small>До проверки информация не считается официальным сообщением.</small></span></div><footer><button type="button" className="outline" onClick={()=>setStep(1)}>{t.cancel}</button><button className="primary"><Send/>{t.publish}</button></footer></form>}</motion.div></motion.div>}
export default App;
