import{AlertTriangle,CalendarDays,CheckCircle2,Wind,Compass,Lightbulb,Leaf,Bus,ShieldAlert,HeartHandshake}from'lucide-react';
export const signals=[
{id:1,pos:[43.648,51.158],kind:'urgent',title:{ru:'Открытый люк у школы №17',kz:'№17 мектеп жанындағы ашық құдық',en:'Open manhole near School 17'},place:{ru:'12 мкр. · 8 мин',kz:'12 ш/а · 8 мин',en:'District 12 · 8 min'},body:{ru:'Высокий риск: рядом школа и остановка.',kz:'Жоғары қауіп: мектеп пен аялдама жақын.',en:'High risk: next to a school and bus stop.'},count:14,status:'working',Icon:AlertTriangle},
{id:2,pos:[43.654,51.171],kind:'event',title:{ru:'Sunset Run Aktau',kz:'Sunset Run Aktau',en:'Sunset Run Aktau'},place:{ru:'Набережная · 19:00',kz:'Жағалау · 19:00',en:'Promenade · 19:00'},body:{ru:'Пять километров у моря на закате.',kz:'Күн батарда теңіз бойымен бес шақырым.',en:'Five kilometers by the sea at sunset.'},count:84,status:'event',Icon:CalendarDays},
{id:3,pos:[43.640,51.151],kind:'solved',title:{ru:'Площадка очищена',kz:'Алаң тазартылды',en:'Site cleaned'},place:{ru:'14 мкр. · 24 мин',kz:'14 ш/а · 24 мин',en:'District 14 · 24 min'},body:{ru:'Служба добавила фото результата.',kz:'Қызмет нәтиже фотосын қосты.',en:'City service uploaded the result photo.'},count:39,status:'resolved',Icon:CheckCircle2},
{id:4,pos:[43.645,51.181],kind:'place',title:{ru:'Скальная тропа',kz:'Жартасты соқпақ',en:'Rock trail'},place:{ru:'Маршрут №3 · 1,8 км',kz:'№3 бағыт · 1,8 км',en:'Route 3 · 1.8 km'},body:{ru:'Панорамная точка у Каспийского моря.',kz:'Каспий теңізінің панорамалық нүктесі.',en:'A panoramic spot by the Caspian Sea.'},count:126,status:'verified',Icon:Compass},
{id:5,pos:[43.658,51.149],kind:'danger',title:{ru:'Сильный боковой ветер',kz:'Қатты жанама жел',en:'Strong crosswind'},place:{ru:'Побережье · 3 мин',kz:'Жағалау · 3 мин',en:'Coast · 3 min'},body:{ru:'Порывы до 18 м/с. Будьте осторожны.',kz:'Екпін 18 м/с дейін. Абай болыңыз.',en:'Gusts up to 18 m/s. Take care.'},count:21,status:'unverified',Icon:Wind},
{id:6,pos:[43.636,51.169],kind:'issue',title:{ru:'Не работает фонарь',kz:'Шам жұмыс істемейді',en:'Streetlight is out'},place:{ru:'17 мкр. · 18 мин',kz:'17 ш/а · 18 мин',en:'District 17 · 18 min'},body:{ru:'Передано службе городского освещения.',kz:'Қалалық жарықтандыру қызметіне берілді.',en:'Assigned to the city lighting service.'},count:7,status:'working',Icon:Lightbulb}];
export const eventsData=[
{date:'28',tone:'eco',title:{ru:'Чистый берег',kz:'Таза жағалау',en:'Clean coast'},place:{ru:'Пляж Маракеш · 09:00',kz:'Маракеш жағажайы · 09:00',en:'Marrakesh beach · 09:00'},people:52},
{date:'30',tone:'culture',title:{ru:'Город у моря',kz:'Теңіз жағасындағы қала',en:'City by the sea'},place:{ru:'Культурный центр · 18:30',kz:'Мәдениет орталығы · 18:30',en:'Culture center · 18:30'},people:31},
{date:'02',tone:'night',title:{ru:'Ночь в музее',kz:'Музейдегі түн',en:'Night at the museum'},place:{ru:'Музей истории · 20:00',kz:'Тарих мұражайы · 20:00',en:'History museum · 20:00'},people:68}];
export const communities=[
{Icon:Leaf,name:{ru:'Eco Aktau',kz:'Eco Aktau',en:'Eco Aktau'},desc:{ru:'Чистый берег и переработка',kz:'Таза жағалау және қайта өңдеу',en:'Clean coast and recycling'},members:'892'},
{Icon:HeartHandshake,name:{ru:'Помощь рядом',kz:'Көмек жанында',en:'Help nearby'},desc:{ru:'Волонтёры и добрые дела',kz:'Еріктілер мен игі істер',en:'Volunteers and good deeds'},members:'674'},
{Icon:Bus,name:{ru:'Удобный транспорт',kz:'Ыңғайлы көлік',en:'Better transport'},desc:{ru:'Маршруты и остановки',kz:'Бағыттар мен аялдамалар',en:'Routes and bus stops'},members:'938'},
{Icon:ShieldAlert,name:{ru:'Безопасный район',kz:'Қауіпсіз аудан',en:'Safe district'},desc:{ru:'Соседи предупреждают соседей',kz:'Көршілер бір-бірін ескертеді',en:'Neighbours keeping each other safe'},members:'1 284'}];
