export const uiText = {
  ru: {
    login: "Войти",
    loginSub: "email или телефон",
    emergencyTitle: "Экстренная помощь",
    emergencyText: "Если есть угроза жизни, пожар или серьёзная авария — звоните 112. twelve не заменяет экстренные службы.",
    call112: "Позвонить 112",
    cancel: "Отмена",
    emergencyTips: ["Сообщите точный адрес", "Кратко опишите ситуацию", "Не покидайте безопасное место"],
    readAll: "Все уведомления прочитаны",
    confirmed: "Подтверждение учтено",
    signInToConfirm: "Войдите, чтобы подтвердить сигнал",
    menu: "Открыть меню",
    closeMenu: "Закрыть меню",
    notifications: "Уведомления",
    theme: "Сменить тему",
    settings: "Настройки",
    onboardingTitle: "Город становится понятнее",
    onboardingText: "Находите события, отмечайте проблемы и следите за тем, как город меняется.",
    onboardingMap: "Смотрите город в реальном времени",
    onboardingSignal: "Создавайте сигналы с фото и геолокацией",
    onboardingResult: "Получайте прозрачный статус решения",
    start: "Начать",
    collapse: "Свернуть приветствие",
    expand: "Показать приветствие",
    routeOpened: "Маршрут открыт",
    reportContent: "Пожаловаться",
    reportSent: "Жалоба отправлена модератору",
    enableNotifications: "Включить уведомления",
    notificationEnabled: "Уведомления включены",
    notificationDenied: "Браузер не разрешил уведомления",
  },
  kz: {
    login: "Кіру",
    loginSub: "email немесе телефон",
    emergencyTitle: "Шұғыл көмек",
    emergencyText: "Өмірге қауіп, өрт немесе ауыр апат болса, 112-ге қоңырау шалыңыз. twelve жедел қызметтерді алмастырмайды.",
    call112: "112-ге қоңырау",
    cancel: "Бас тарту",
    emergencyTips: ["Нақты мекенжайды айтыңыз", "Жағдайды қысқа сипаттаңыз", "Қауіпсіз жерден кетпеңіз"],
    readAll: "Барлық хабарлама оқылды",
    confirmed: "Растау қабылданды",
    signInToConfirm: "Белгіні растау үшін кіріңіз",
    menu: "Мәзірді ашу",
    closeMenu: "Мәзірді жабу",
    notifications: "Хабарламалар",
    theme: "Тақырыпты ауыстыру",
    settings: "Баптаулар",
    onboardingTitle: "Қаланы түсіну оңай",
    onboardingText: "Оқиғаларды табыңыз, мәселелерді белгілеңіз және қаланың өзгерісін бақылаңыз.",
    onboardingMap: "Қаланы нақты уақытта көріңіз",
    onboardingSignal: "Фото және геолокациямен белгі жасаңыз",
    onboardingResult: "Шешім мәртебесін ашық бақылаңыз",
    start: "Бастау",
    collapse: "Сәлемдесуді жасыру",
    expand: "Сәлемдесуді көрсету",
    routeOpened: "Бағыт ашылды",
    reportContent: "Шағымдану",
    reportSent: "Шағым модераторға жіберілді",
    enableNotifications: "Хабарламаларды қосу",
    notificationEnabled: "Хабарламалар қосылды",
    notificationDenied: "Браузер хабарламаларға рұқсат бермеді",
  },
  en: {
    login: "Sign in",
    loginSub: "email or phone",
    emergencyTitle: "Emergency help",
    emergencyText: "If life is at risk, there is a fire or a serious accident, call 112. twelve does not replace emergency services.",
    call112: "Call 112",
    cancel: "Cancel",
    emergencyTips: ["Give the exact address", "Describe the situation briefly", "Stay in a safe place"],
    readAll: "All notifications marked as read",
    confirmed: "Confirmation recorded",
    signInToConfirm: "Sign in to confirm this signal",
    menu: "Open menu",
    closeMenu: "Close menu",
    notifications: "Notifications",
    theme: "Change theme",
    settings: "Settings",
    onboardingTitle: "A city that makes sense",
    onboardingText: "Discover events, report issues and follow visible city change.",
    onboardingMap: "See the city in real time",
    onboardingSignal: "Create signals with a photo and location",
    onboardingResult: "Follow a transparent resolution status",
    start: "Get started",
    collapse: "Collapse welcome",
    expand: "Show welcome",
    routeOpened: "Route opened",
    reportContent: "Report content",
    reportSent: "Report sent to moderators",
    enableNotifications: "Enable notifications",
    notificationEnabled: "Notifications enabled",
    notificationDenied: "Browser notifications were denied",
  },
};